import "./globals.scss";
import type { Metadata } from "next";
import { Suspense } from "react";
import { Inter } from "next/font/google";
import Providers from "@/components/Navbar/Providers";
const inter = Inter({ subsets: ["latin"] });
import Loader from "@/components/Loader/Loader";
import Navbar from "@/components/Navbar/Navbar";

export const metadata: Metadata = {
  metadataBase: new URL("http://abujfor.com/"),
  title: {
    default: "Quick Dev Interview Preparation",
    template: ` %s | Quick Dev Interview Preparation`
  },
  description: "Generated by create next app",
  verification: {
    google: "google-site-verification=123123123"
  }
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Suspense fallback={<Loader />}>{children}</Suspense>
        </Providers>
      </body>
    </html>
  );
}
