import React from "react";
import { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";

import { getAllResource } from "@/app/utils/resourceDataFetch";



export const metadata: Metadata = {
  title: "Resources | Quick Dev Interview Preparation",
  description: "Generated by create next app",
};

type FormDataType = {
  _id: string,
  user: string;
  title: string;
  shortDescription: string;
  image: string;
  description: string;
  isPublished: boolean;
  topNews: boolean;
  topOthers: boolean;
  tag: string;
  popular: boolean;
  category: string;
  categoryName: string;
};

type propsType = {
  resources: FormDataType[]
}

const page = async () => {
  const resources = await getAllResource();
  const recent: FormDataType[] = [];
  const popular: FormDataType[] = [];
  const top: FormDataType[] = [];
  let main = { _id: '',
  user: '',
  title: '',
  shortDescription: '',
  image: '',
  description: '',
  isPublished: false,
  topNews: false,
  topOthers: false,
  tag: '',
  popular: false,
  category: '',
  categoryName: ''};

  if(resources){
    resources.forEach( (item, index) => {
      if(index < 3){
        recent.push(item);
      }
      if(item.popular){
        popular.push(item);
      }
      if(item.topNews){
        top.push(item);
      }
      if(item.topNews){
        main = item;
      }
    })
  }
  

  return (
    <div className="max-w-screen-xl mx-auto">
      <div className="mt-12 ml-auto mr-auto w-full">
        <h1 className="mb-4 text-4xl text-center font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-6xl dark:text-white">
          Tech Toolbox: Your Gateway to Essential Tech Resources and Expert
          Insights
        </h1>
        <p className="mb-6 text-lg font-normal text-gray-500 lg:text-xl sm:px-16 xl:px-48 dark:text-gray-400">
          Discover a wealth of curated tech resources, tips, and insights to
          empower your tech journey. Maximize productivity and embrace
          innovation with Tech Toolbox.
        </p>
      </div>

      <main className="mt-6">
        <div className="flex items-start lg:flex-row flex-col gap-3 ">
          <div className="self-start lg:w-7/12 mb-4 lg:mb-0 p-4 lg:p-0 rounded block">
            { main?.image  ? (
            <Image
            src={main.image}
            className="rounded-md object-cover w-full h-64"
            alt={main.title}
            width={400}
            height={400}
          />) : null
          }
            
            <span className="text-green-700 text-sm hidden md:block mt-4">
              {main.categoryName}
            </span>
            <h1 className="text-gray-800 text-4xl font-bold mt-2 mb-2 leading-tight">
              {main.title}
            </h1>
            
            <div
                  className="text-gray-600 mb-4"
                >
                  <p>
                  {main.shortDescription.slice(0,150)}
                  </p>
                </div>
            
            <Link
              href="./blog.html"
              className="inline-block px-6 py-3 mt-2 rounded-md bg-green-700 text-gray-100"
            >
              Read more
            </Link>
          </div>

          <div className="self-start lg:w-5/12">
            <div className="flex flex-col gap-3">

              { top.map((item) => (
                <div className="flex flex-row rounded mb-10" key={item._id}>
                  { item?.image ? (
                <Image
                  src={item.image}
                  className="block md:hidden lg:block rounded-md h-64 md:h-32 m-4 md:m-0"
                  alt={item.title}
                  width={200}
            height={200}
                />
                  ): null
                  }
                <div className="bg-white rounded px-4">
                  <span className="text-green-700 text-sm hidden md:block">
                    {item.categoryName}
                  </span>
                  <div className="md:mt-0 text-gray-800 font-semibold text-xl mb-2">
                    {item.title}
                  </div>
                  <div className="block md:hidden p-2 pl-0 pt-1 text-sm text-gray-600">
                    <p>
                    {item.shortDescription.slice(0,150)}
                    </p>
                  </div>
                </div>
              </div>
              ))}
            </div>
          </div>
        </div>




        <div className="flex mt-16 mb-4 px-4 lg:px-0 items-center justify-between">
          <h2 className="font-bold text-3xl">Latest news</h2>
          <Link href="/" className="bg-gray-200 hover:bg-green-200 text-gray-800 px-3 py-1 rounded cursor-pointer">
            View all
          </Link>
        </div>

        
          <div className="block space-x-0 lg:flex lg:space-x-6" >
          { recent.map((item) => (
          <div className="rounded w-full lg:w-1/2 lg:w-1/3 p-4 lg:p-0" key={item._id}>
          { item?.image  ? (
            <Image
            src={item.image}
            className="rounded-md object-cover w-full h-64"
            alt={item.title}
            width={200}
            height={200}
          />) : null
          }
            <div className="p-4 pl-0">
              <h2 className="font-bold text-2xl text-gray-800">
                {item.title}
              </h2>
              <div className="text-gray-700 mt-2">
              <p>
                    {item.shortDescription.slice(0,150)}
                    </p>
              </div>

              <Link
                href={`/resource/${item._id}`}
                className="inline-block py-2 rounded text-green-900 mt-2 ml-auto"
              >
                {" "}
                Read more{" "}
              </Link>
            </div>
          </div>
          ))}
        </div>
        
        

        <div className="rounded flex md:shadow mt-12">
          <img
            src="https://images.unsplash.com/photo-1579275542618-a1dfed5f54ba?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=900&q=60"
            className="w-0 md:w-1/4 object-cover rounded-l"
          />
          <div className="px-4 py-2">
            <h3 className="text-3xl text-gray-800 font-bold">
              Subscribe to newsletter
            </h3>
            <p className="text-xl text-gray-700">
              We sent latest news and posts once in every week, fresh from the
              oven
            </p>
            <form className="mt-4 mb-10">
              <input
                type="email"
                className="rounded bg-gray-100 px-4 py-2 border focus:border-green-400"
                placeholder="john@tech.com"
              />
              <button className="px-4 py-2 rounded bg-green-800 text-gray-100">
                Subscribe
                <i className="bx bx-right-arrow-alt"></i>
              </button>
              <p className="text-green-900 opacity-50 text-sm mt-1">
                No spam. We promise
              </p>
            </form>
          </div>
        </div>

        <div className="flex mt-16 mb-4 px-4 lg:px-0 items-center justify-between">
          <h2 className="font-bold text-3xl">Popular news</h2>
          <Link href="#" className="bg-gray-200 hover:bg-green-200 text-gray-800 px-3 py-1 rounded cursor-pointer">
            View all
          </Link>
        </div>
        <div className="block space-x-0 lg:flex lg:space-x-6" >
          { popular.map((item) => (
          <div className="rounded w-full lg:w-1/2 lg:w-1/3 p-4 lg:p-0" key={item._id}>
          { item?.image  ? (
            <Image
            src={item.image}
            className="rounded-md object-cover w-full h-64"
            alt={item.title}
            width={200}
            height={200}
          />) : null
          }
            <div className="p-4 pl-0">
              <h2 className="font-bold text-2xl text-gray-800">
                {item.title}
              </h2>
              <div className="text-gray-700 mt-2">
              <p>
                    {item.shortDescription.slice(0,150)}
                    </p>
              </div>

              <Link
                href={`/resource/${item._id}`}
                className="inline-block py-2 rounded text-green-900 mt-2 ml-auto"
              >
                {" "}
                Read more{" "}
              </Link>
            </div>
          </div>
          ))}
        </div>
      </main>
    </div>
  );
};

export default page;
