import React from "react";
import { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";

import { getAllResource, getAllCategory } from "@/app/utils/resourceDataFetch";

export const metadata: Metadata = {
  title: "Resources | Quick Dev Interview Preparation",
  description: "Generated by create next app"
};

type FormDataType = {
  _id: string;
  slug: string,
  user: string;
  title: string;
  shortDescription: string;
  image: string;
  description: string;
  isPublished: boolean;
  topNews: boolean;
  topOthers: boolean;
  tag: string;
  popular: boolean;
  category: string;
  categoryName: string;
};

type propsType = {
  resources: FormDataType[];
};

const page = async () => {
  const resources = await getAllResource();
  const category = await getAllCategory();
  const recent: FormDataType[] = [];
  const popular: FormDataType[] = [];
  const top: FormDataType[] = [];
  let main = {
    _id: "",
    slug: "",
    user: "",
    title: "",
    shortDescription: "",
    image: "",
    description: "",
    isPublished: false,
    topNews: false,
    topOthers: false,
    tag: "",
    popular: false,
    category: "",
    categoryName: ""
  };

  if (resources) {
    resources.forEach((item, index) => {
      if (index < 3) {
        recent.push(item);
      }
      if (item.popular) {
        popular.push(item);
      }
      if (item.topNews) {
        top.push(item);
      }
      if (item.topNews) {
        main = item;
      }
    });
  }

  return (
    <div className="max-w-screen-xl mx-auto">
      <section className="text-gray-600 body-font">
        <div className="container px-5 pt-24 pb-10 mx-auto">
          <div className="text-center mb-20">
            <h1 className="sm:text-3xl text-2xl font-medium title-font text-gray-900 mb-4">
              Essential Tech Resources and Expert Guidelines
            </h1>
            <p className="text-base leading-relaxed xl:w-2/4 lg:w-3/4 mx-auto text-gray-500s">
            Unlock the power of technology with curated resources and expert guidelines. Maximize productivity and embrace innovation on your tech journey.
            </p>
            <div className="flex mt-6 justify-center">
              <div className="w-16 h-1 rounded-full bg-indigo-500 inline-flex"></div>
            </div>
          </div>
          <div className="flex flex-wrap sm:-m-4 -mx-4 -mb-10 -mt-4 md:space-y-0 space-y-6">
            {category.map((item) => (
              <div
                key={item._id}
                className="p-4 md:w-1/3 flex flex-col text-center items-center"
              >
                <div className="w-8/12 sm:w-7/12 px-4 inline-flex items-center justify-center mb-5">
                  <Image
                    src={item.image}
                    alt="Category Image"
                    height={200}
                    width={200}
                    className="shadow-lg rounded-md max-w-full h-auto align-middle border-none"
                  />
                </div>
                <div className="flex-grow">
                  <h2 className="text-gray-900 text-lg title-font font-medium mb-3">
                    {item.name}
                  </h2>
                  <p className="leading-relaxed text-base">
                    {item.description}
                  </p>
                  <Link
                    href={`resources/category/${item.slug}`}
                    className="mt-3 text-indigo-500 inline-flex items-center"
                  >
                    Learn More
                    <svg
                      fill="none"
                      stroke="currentColor"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      className="w-4 h-4 ml-2"
                      viewBox="0 0 24 24"
                    >
                      <path d="M5 12h14M12 5l7 7-7 7"></path>
                    </svg>
                  </Link>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <main className="mt-6">
        <section className="text-gray-600 body-font">
          <div className="container px-5 py-10 mx-auto">
            <div className="flex flex-col">
              <div className="h-1 bg-gray-200 rounded overflow-hidden">
                <div className="w-24 h-full bg-indigo-500"></div>
              </div>
              <div className="flex flex-wrap sm:flex-row flex-col py-6 mb-12">
                <h1 className="sm:w-2/5 text-gray-900 font-medium title-font text-2xl mb-2 sm:mb-0">
                  
📌 Featured & Popular Blogs 🌟
                </h1>
                <p className="sm:w-3/5 leading-relaxed text-base sm:pl-10 pl-0">
                Explore our most viewed and popular posts! Stay ahead of the curve with the hottest topics and sought-after content. Join the buzz and dive into the best of tech.🚀💡
                </p>
              </div>
            </div>
            <div className="flex flex-wrap sm:-m-4 -mx-4 -mb-10 -mt-4">
              <div className="p-4 md:w-1/3 sm:mb-0 mb-6">
                <div className="rounded-lg h-48 overflow-hidden">
                  {main?.image ? (
                    <Image
                      src={main.image}
                      alt={main.title}
                      width={300}
                      height={300}
                    />
                  ) : null}
                </div>
                <h2 className="text-xl font-medium title-font text-gray-900 mt-5">
                  {main.title}
                </h2>
                <p className="text-base leading-relaxed mt-2">
                  {main.shortDescription.slice(0, 150)}
                </p>
                <Link
                  href={`/resources/details/${main.slug}`}
                  className="text-indigo-500 inline-flex items-center mt-3"
                >
                  Learn More
                  <svg
                    fill="none"
                    stroke="currentColor"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    className="w-4 h-4 ml-2"
                    viewBox="0 0 24 24"
                  >
                    <path d="M5 12h14M12 5l7 7-7 7"></path>
                  </svg>
                </Link>
              </div>

              {top.map((item) => (
                <div key={item._id} className="p-4 md:w-1/3 sm:mb-0 mb-6">
                  <div className="rounded-lg h-48 overflow-hidden">
                    {item?.image ? (
                      <Image
                        src={item.image}
                        alt={item.title}
                        width={300}
                        height={300}
                      />
                    ) : null}
                  </div>
                  <h2 className="text-xl font-medium title-font text-gray-900 mt-5">
                    {item.title}
                  </h2>
                  <p className="text-base leading-relaxed mt-2">
                    {item.shortDescription.slice(0, 150)}
                  </p>
                  <Link
                    href={`/resources/details/${item.slug}`}
                    className="text-indigo-500 inline-flex items-center mt-3"
                  >
                    Learn More
                    <svg
                      fill="none"
                      stroke="currentColor"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      className="w-4 h-4 ml-2"
                      viewBox="0 0 24 24"
                    >
                      <path d="M5 12h14M12 5l7 7-7 7"></path>
                    </svg>
                  </Link>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section className="text-gray-600 body-font">
          <div className="container px-5 py-10 mx-auto">
            <div className="flex flex-col">
              <div className="h-1 bg-gray-200 rounded overflow-hidden">
                <div className="w-24 h-full bg-indigo-500"></div>
              </div>
              <div className="flex flex-wrap sm:flex-row flex-col py-6 mb-12">
                <h1 className="sm:w-2/5 text-gray-900 font-medium title-font text-2xl mb-2 sm:mb-0">
                🌟 Latest Blogs: Stay Updated! 🌟
                </h1>
                <p className="sm:w-3/5 leading-relaxed text-base sm:pl-10 pl-0">
                Explore our newest blog posts! From tech tips to industry news, our concise reads will keep you in the loop with the latest trends. Level up your tech game with expert insights - dive in now! 💡🚀
                </p>
              </div>
            </div>
            <div className="flex flex-wrap sm:-m-4 -mx-4 -mb-10 -mt-4">
              {recent.map((item) => (
                <div key={item._id} className="p-4 md:w-1/3 sm:mb-0 mb-6">
                  <div className="rounded-lg h-48 overflow-hidden">
                    {item?.image ? (
                      <Image
                        src={item.image}
                        alt={item.title}
                        width={300}
                        height={300}
                      />
                    ) : null}
                  </div>
                  <h2 className="text-xl font-medium title-font text-gray-900 mt-5">
                    {item.title}
                  </h2>
                  <p className="text-base leading-relaxed mt-2">
                    {item.shortDescription.slice(0, 150)}
                  </p>
                  <Link
                    href={`/resources/details/${item.slug}`}
                    className="text-indigo-500 inline-flex items-center mt-3"
                  >
                    Learn More
                    <svg
                      fill="none"
                      stroke="currentColor"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      className="w-4 h-4 ml-2"
                      viewBox="0 0 24 24"
                    >
                      <path d="M5 12h14M12 5l7 7-7 7"></path>
                    </svg>
                  </Link>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section className="text-gray-600 body-font">
          <div className="container px-5 py-10 mx-auto">
            <div className="flex flex-col">
              <div className="h-1 bg-gray-200 rounded overflow-hidden">
                <div className="w-24 h-full bg-indigo-500"></div>
              </div>
              <div className="flex flex-wrap sm:flex-row flex-col py-6 mb-12">
                <h1 className="sm:w-2/5 text-gray-900 font-medium title-font text-2xl mb-2 sm:mb-0">
                🔥 Hot Blogs: Top Picks! 🔥
                </h1>
                <p className="sm:w-3/5 leading-relaxed text-base sm:pl-10 pl-0">
                Dive into our top-rated blog posts, handpicked for you! Stay in the loop with trending tech topics and valuable insights. Find out what&apos;s making waves and get inspired by the best content around. Check out our hottest reads and join the tech-savvy community today! 🚀💡
                </p>
              </div>
            </div>
            <div className="flex flex-wrap sm:-m-4 -mx-4 -mb-10 -mt-4">
              {popular.map((item) => (
                <div key={item._id} className="p-4 md:w-1/3 sm:mb-0 mb-6">
                  <div className="rounded-lg h-48 overflow-hidden">
                    {item?.image ? (
                      <Image
                        src={item.image}
                        alt={item.title}
                        width={300}
                        height={300}
                      />
                    ) : null}
                  </div>
                  <h2 className="text-xl font-medium title-font text-gray-900 mt-5">
                    {item.title}
                  </h2>
                  <p className="text-base leading-relaxed mt-2">
                    {item.shortDescription.slice(0, 150)}
                  </p>
                  <Link
                    href={`/resources/details/${item.slug}`}
                    className="text-indigo-500 inline-flex items-center mt-3"
                  >
                    Learn More
                    <svg
                      fill="none"
                      stroke="currentColor"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      className="w-4 h-4 ml-2"
                      viewBox="0 0 24 24"
                    >
                      <path d="M5 12h14M12 5l7 7-7 7"></path>
                    </svg>
                  </Link>
                </div>
              ))}
            </div>
          </div>
        </section>
      </main>
    </div>
  );
};

export default page;
